config/routes.rb
Rails.application.routes.draw do

  resources :reservations
  get "reservations/:id/remove", to: 'reservations#destroy', as: 'destroy_reservation'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :items, except: [:new, :create]

  resources :products
  post "products/validate", to: 'products#validate', as: 'validate_product'
  get "products/:id/remove", to: 'products#destroy', as: 'destroy_product'

  resources :stablishments

  #post "carts/add_item/:product_id", to: "carts#add_item", as: 'add_item_to_cart'
  delete "carts/remove_item/:item_id", to: "carts#remove_item", as: 'remove_item_from_cart'

  get "items/new/:product_id", to: 'items#new', as: 'new_item'
  get "items/:id/checkout", to: "items#checkout", as: 'checkout_item'
  post "items/create/:product_id", to: 'items#create', as: 'create_item'

  get 'home/index'
  get 'home/checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/item.rb
class Item < ApplicationRecord
    include ActionView::Helpers::NumberHelper

    belongs_to :product

    def total_value
        quantity * price
    end

    def price_format
        number_to_currency(self.price, :unit => "R$ ", :separator => ",", :delimiter => ".")
    end

    def total_format
        number_to_currency(self.total_value, :unit => "R$ ", :separator => ",", :delimiter => ".")
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:create, :new, :update, :edit]

  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.create(
      name: @product.name,
      quantity: item_params[:quantity],
      price: @product.price,
      date: Time.now,
      product_id: @product.id
    )

    @product.update_attributes(
        quantity: @product.quantity - @item.quantity,
    )

    @reservation = Reservation.create(
      initial_date: reservation_initial_date,
      final_date: reservation_final_date,
      obs: reservation_params[:obs],
      user: current_user,
      item: @item,
    )

    redirect_to @item

    # respond_to do |format|
    #   if !(@product.errors.any? || @item.errors.any? ||
    #        @reservation.errors.any?)
    #       format.html { redirect_to @item, status: :created }
    #       format.json { render :show, status: :created, location: @item }
    #   else
    #     format.html { redirect_to root_path }
    #     format.json { render json: @item.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  def checkout

  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :quantity, :price, :date)
    end

    def reservation_params
      params.require(:reservation).permit( :initial_date, :final_date, :obs )
    end

    def current_user_cart
      if current_user.reload.cart.blank?
        Cart.create(user_id: current_user.id, date: Time.now)
      else
        current_user.reload.cart
      end
    end

    #


    def reservation_initial_date
      DateTime.new(   reservation_params["initial_date(1i)"].to_i,
                      reservation_params["initial_date(2i)"].to_i,
                      reservation_params["initial_date(3i)"].to_i,
                      reservation_params["initial_date(4i)"].to_i,
                      reservation_params["initial_date(5i)"].to_i
                  )
    end

    def reservation_final_date
      DateTime.new(   reservation_params["final_date(1i)"].to_i,
                      reservation_params["final_date(2i)"].to_i,
                      reservation_params["final_date(3i)"].to_i,
                      reservation_params["final_date(4i)"].to_i,
                      reservation_params["final_date(5i)"].to_i
                  )
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for :item , url: create_item_path(product_id: @product) do |f| %>

  <%= fields_for :reservation do |reservation_fields| %>
    <div class="form-group">
      <%= reservation_fields.label 'Data Inicial'%>
      <%= reservation_fields.datetime_select :initial_date, id: :reservation_initial_date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= reservation_fields.label 'Data Final'%>
      <%= reservation_fields.datetime_select :final_date, id: :reservation_initial_date, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= reservation_fields.label 'Observação' %>
      <%= reservation_fields.text_area :obs, class: 'form-control' %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :quantidade %>
    <%= f.text_field :quantity, class: 'form-control' %>
  </div>

  <%= f.submit 'Salvar', class: 'btn btn-red btn-block mb-30'%>
<% end %>

app/views/items/_original_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :item_quantity %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :item_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Visualizar', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table class="tabela">
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
        <td><%= item.date %></td>
        <td><%= link_to 'Visualizar', item %></td>
        <td><%= link_to 'Editar', edit_item_path(item) %></td>
        <td><%= link_to 'Remover', item, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/items/new.html.erb
<div class="title container">
  Nova Reserva
</div>

<div class="container">
  <%= render 'form', item: @item %>
</div>

app/views/items/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="text-center">
    <div class="product-title">
      <h1>
        <%= @item.name %>
      </h1>
    </div>

    <strong>Preço:</strong>
    <div class="product-price"><%= @item.price_format %></div>

    <strong>Quantidade:</strong>
    <div class="product-price"><%= @item.quantity %></div>

    <strong>Total:</strong>
    <div class="product-price"><%= @item.total_format %></div>

    <%= link_to 'Finalizar Compra', home_checkout_path, class: 'btn btn-red btn-lg'%>
  </div>
</div>