config/routes.rb
Rails.application.routes.draw do

  resources :reservations
  get "reservations/:id/remove", to: 'reservations#destroy', as: 'destroy_reservation'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :items, except: [:new, :create]

  resources :products
  post "products/validate", to: 'products#validate', as: 'validate_product'
  get "products/:id/remove", to: 'products#destroy', as: 'destroy_product'

  resources :stablishments

  #post "carts/add_item/:product_id", to: "carts#add_item", as: 'add_item_to_cart'
  delete "carts/remove_item/:item_id", to: "carts#remove_item", as: 'remove_item_from_cart'

  get "items/new/:product_id", to: 'items#new', as: 'new_item'
  get "items/:id/checkout", to: "items#checkout", as: 'checkout_item'
  post "items/create/:product_id", to: 'items#create', as: 'create_item'

  get 'home/index'
  get 'home/checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/stablishment.rb
class Stablishment < ApplicationRecord
  belongs_to :company_user, class_name: "CompanyUser", foreign_key: "user_id"

  alias_method :user, :company_user
end

app/controllers/stablishments_controller.rb
class StablishmentsController < ApplicationController
  before_action :set_stablishment, only: [:show, :edit, :update, :destroy]

  # GET /stablishments
  # GET /stablishments.json
  def index
    @stablishments = Stablishment.all
  end

  # GET /stablishments/1
  # GET /stablishments/1.json
  def show
  end

  # GET /stablishments/new
  def new
    @stablishment = Stablishment.new
  end

  # GET /stablishments/1/edit
  def edit
  end

  # POST /stablishments
  # POST /stablishments.json
  def create
    @stablishment = Stablishment.new(stablishment_params)
    @stablishment.company_user = current_user
    respond_to do |format|
      if @stablishment.save
        format.html { redirect_to @stablishment, notice: 'Stablishment was successfully created.' }
        format.json { render :show, status: :created, location: @stablishment }
      else
        format.html { render :new }
        format.json { render json: @stablishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stablishments/1
  # PATCH/PUT /stablishments/1.json
  def update
    respond_to do |format|
      if @stablishment.update(stablishment_params)
        format.html { redirect_to @stablishment, notice: 'Stablishment was successfully updated.' }
        format.json { render :show, status: :ok, location: @stablishment }
      else
        format.html { render :edit }
        format.json { render json: @stablishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stablishments/1
  # DELETE /stablishments/1.json
  def destroy
    @stablishment.destroy
    respond_to do |format|
      format.html { redirect_to stablishments_url, notice: 'Stablishment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stablishment
      @stablishment = Stablishment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stablishment_params
      params.require(:stablishment).permit(:address, :name, :country, :phone, :phone2, :cnpj, :fantasy)
    end
end

app/helpers/stablishments_helper.rb
module StablishmentsHelper
end

app/views/stablishments/_form.html.erb
<%= form_with(model: stablishment, local: true) do |form| %>
  <% if stablishment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stablishment.errors.count, "error") %> prohibited this stablishment from being saved:</h2>

      <ul>
      <% stablishment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :stablishment_address %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :stablishment_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :stablishment_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stablishments/edit.html.erb
<h1>Editing Stablishment</h1>

<%= render 'form', stablishment: @stablishment %>

<%= link_to 'Visualizar', @stablishment %> |
<%= link_to 'Back', stablishments_path %>

app/views/stablishments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stablishments</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Name</th>
      <th>User</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stablishments.each do |stablishment| %>
      <tr>
        <td><%= stablishment.address %></td>
        <td><%= stablishment.name %></td>
        <td><%= stablishment.user.email %></td>
        <td><%= stablishment.phone %></td>
        <td><%= link_to 'Visualizar', stablishment %></td>
        <td><%= link_to 'Editar', edit_stablishment_path(stablishment) %></td>
        <td><%= link_to 'Remover', stablishment, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stablishment', new_stablishment_path %>

app/views/stablishments/new.html.erb
<h1>New Stablishment</h1>

<%= render 'form', stablishment: @stablishment %>

<%= link_to 'Back', stablishments_path %>

app/views/stablishments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @stablishment.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stablishment.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @stablishment.company_user.email %>
</p>


<p>
  <strong>Phone:</strong>
  <%= @stablishment.phone %>
</p>


<%= link_to 'Editar', edit_stablishment_path(@stablishment) %> |
<%= link_to 'Back', stablishments_path %>