config/routes.rb
Rails.application.routes.draw do

  resources :reservations
  get "reservations/:id/remove", to: 'reservations#destroy', as: 'destroy_reservation'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :items, except: [:new, :create]

  resources :products
  post "products/validate", to: 'products#validate', as: 'validate_product'
  get "products/:id/remove", to: 'products#destroy', as: 'destroy_product'

  resources :stablishments

  #post "carts/add_item/:product_id", to: "carts#add_item", as: 'add_item_to_cart'
  delete "carts/remove_item/:item_id", to: "carts#remove_item", as: 'remove_item_from_cart'

  get "items/new/:product_id", to: 'items#new', as: 'new_item'
  get "items/:id/checkout", to: "items#checkout", as: 'checkout_item'
  post "items/create/:product_id", to: 'items#create', as: 'create_item'

  get 'home/index'
  get 'home/checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/product.rb
class Product < ApplicationRecord
    include ActionView::Helpers::NumberHelper

    has_many :items

    def price_format
        number_to_currency(self.price, :unit => "R$ ", :separator => ",", :delimiter => ".")
    end

    def get_image
        return "/resources/images/product"+rand(1...5).to_s+".png" unless self.image
        return "/resources/images/"+self.image.to_s
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :can_commit, only: [:create, :new, :update, :edit]

  skip_before_action :authenticate_user!, only: [:show]

  # GET /products
  # GET /products.json
  def can_commit
    if current_user.is_human?
      flash[:alert] = "Apenas usuários empresas podem editar"
      redirect_to root_path if current_user.is_human?
    end
  end

  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def validate
    begin
      @reservation = Reservation.find(params[:code])
      flash[:notice] = { status: 'success', msg: "Reserva Válida \n Usuário: " + @reservation.user.email + " \n Produto: " + @reservation.item.product.name + " \n Data Inicial: " + @reservation.initial_date.strftime("%d/%m/%Y %H:%m") + " \n Data Final: " + @reservation.final_date.strftime("%d/%m/%Y %H:%m") }
      redirect_to products_path
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = { status: 'warning', msg: 'Reserva Inválida' }
      redirect_to products_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :quantity, :price, :address, :stablishment_id, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :name, id: :product_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :descricao %>
    <%= form.text_area :description, id: :product_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantidade %>
    <%= form.number_field :quantity, id: :product_quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :preço %>
    <%= form.text_field :price, id: :product_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :endereço %>
    <%= form.text_field :address, id: :product_address, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary", value: "Salvar" %>
<% end %>

app/views/products/edit.html.erb
<div class="title container">
  Editar Produto
</div>

<div class="container">
  <%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<div class="title container">
  Meus Produtos
</div>

<div class="container">
  <%= form_tag("/products/validate", method: "post", class: 'form-inline') do %>
    <%= text_field_tag(:code, '', { placeholder: 'Código da reserva', class: 'form-control'}) %>
    <%= submit_tag("Validar Reserva", class: 'btn btn-red') %>
  <% end %>

  <br><br>

  <%= link_to 'Criar Produto', new_product_path, class: 'btn btn-red' %>

  <table class="table">
    <thead>
      <tr>
        <th class="text-center">Nome</th>
        <th class="text-center">Quantidade</th>
        <th class="text-center">Preço</th>
        <th class="text-center">Endereço</th>
        <th colspan="4"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
            <td class="text-center"><%= product.name %></td>
            <td class="text-center"><%= product.quantity %></td>
            <td class="text-center"><%= product.price_format %></td>
            <td class="text-center"><%= product.address %></td>
            <td class="text-center"><%= link_to 'Visualizar', product %></td>
            <td class="text-center"><%= link_to 'Editar', edit_product_path(product) %></td>
            <td class="text-center">
              <% if product.items.size > 0 %>
                Impossível remover produto.
              <% else %>
                <%= link_to 'Remover', destroy_product_path(product) %>
              <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="title container">
  Novo Produto
</div>

<div class="container">
  <%= render 'form', product: @product %>
</div>

app/views/products/show.html.erb
<div style="padding: 40px 80px;background:#eeeeee;">
    <div class="container">
        <div style="background:white;margin-bottom:30px;display:flex;align-items:center;padding:30px 20px;border-radius:15px">
            <div>
                <div style="margin-bottom:5px; font-size: 35px;">
                    <%= @product.name %>
                </div>
                <div class="product-rate">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="far fa-star"></i>
                    <i class="far fa-star"></i>
                </div>
            </div>
            <div style="flex-grow:1;display:flex;flex-direction:row-reverse;align-items:center">
                <% if user_signed_in? %>
                    <%= link_to 'Reservar Agora', new_item_path(@product), class: "btn btn-red" %>
                <% end %>
                <span style="margin-right:30px;font-size:40px;color:grey"><%= @product.price_format %></span>
            </div>
        </div>
        <div style="display:flex;align-items:stretch;border-radius:15px;overflow:hidden">
            <div class="col-md-12 row" style="background:white">
                <div class="col-md-5 hidden-xs hidden-sm" style="height: 100%; background-image: url('<%= @product.get_image %>'); background-size: cover; background-repeat: no-repeat; background-position: center;">
                </div>

                <div class="col-md-7" style="padding:50px 40px; display: inline-block;">
                    <div class="product-detail-title mb-30" >
                        Descrição
                    </div>
                    <div class="product-detail-description">
                        <%= @product.description %>
                    </div>
                    <div class="product-detail-title mb-30 mt-30">
                        Endereço
                    </div>
                    <div class="product-detail-description">
                    <%= @product.address %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/products/validate.html.erb
<div class="container">
  <% if @reservation %>
  <% else %>
    <h2>Reserva inválida</h2>
  <% end %>
</div>