config/routes.rb
Rails.application.routes.draw do

  resources :reservations
  get "reservations/:id/remove", to: 'reservations#destroy', as: 'destroy_reservation'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :items, except: [:new, :create]

  resources :products
  post "products/validate", to: 'products#validate', as: 'validate_product'
  get "products/:id/remove", to: 'products#destroy', as: 'destroy_product'

  resources :stablishments

  #post "carts/add_item/:product_id", to: "carts#add_item", as: 'add_item_to_cart'
  delete "carts/remove_item/:item_id", to: "carts#remove_item", as: 'remove_item_from_cart'

  get "items/new/:product_id", to: 'items#new', as: 'new_item'
  get "items/:id/checkout", to: "items#checkout", as: 'checkout_item'
  post "items/create/:product_id", to: 'items#create', as: 'create_item'

  get 'home/index'
  get 'home/checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/layouts/_header.html.erb
<div id="head">
    <%= link_to("Turismaria", home_index_path, class: "header-logo") %>
    <div>
        <% if user_signed_in? %>
            <%= link_to('Sair', destroy_user_session_path, class: "header-btn", style: "float:right") %>
            <% if current_user.is_human? %>
                <%= link_to('Minhas Reservas', reservations_path, class: "header-btn", style: "float:right") %>
            <% else %>
                <%= link_to('Meus Produtos', products_path, class: "header-btn", style: "float:right") %>
            <% end %>
        <% else %>
            <span style="float:right" class="header-btn" id="EntrarButton">
                Entrar
            </span>
        <% end %>
    </div>
</div>

app/views/layouts/_modals.html.erb
<div class="dimmer""></div>
<div id="ModalLogin" class="modal-container">
  <div>
    <div class="modal-turismaria">
      <div class="modal-close">
        <i class="fa fa-times"></i>
      </div>

      <div class="LoginContainer">
        <%= form_for(resource_name, :as => resource_name, :url => session_path(resource_name)) do |f| %>
          <div style="text-align:center;margin-bottom:40px">
            TURISMARIA
          </div>

          <%= devise_error_messages! %>

          <div class="input-login mb-15">
            <div>
              <div>
                <i class="fa fa-at"></i>
              </div>
              <%= f.email_field :email, placeholder: "Email" %>
            </div>
          </div>
          <div class="input-login mb-15">
            <div>
              <div>
                <i class="fa fa-key"></i>
              </div>
              <%= f.password_field :password, placeholder: "Senha" %>
            </div>
          </div>

          <%= f.submit "Entrar", class: "btn btn-red btn-block mb-30" %>

          <div style="color:grey;text-align:center;font-size:17px;">
            Não possui uma conta?
          </div>
          <div id="ButtonCadastro" onclick="OpenCadastroForm()" style="">
            Cadastre-se Agora
          </div>
        <% end %>
      </div>


      <div class="CadastroContainer" style="display:none">
        <%= form_for(resource_name, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <div style="color:grey;text-align:center;font-size:22px;margin-bottom:30px">
            Efetue seu cadastro agora
          </div>

          <%= devise_error_messages! %>

          <div class="input-login mb-15">
            <div>
              <div>
                <i class="fa fa-user"></i>
              </div>
              <%= f.text_field :name, placeholder: "Nome" %>
            </div>
          </div>
          <div class="input-login mb-15">
            <div>
              <div>
                <i class="fa fa-at"></i>
              </div>
              <%= f.email_field :email, placeholder: "Email" %>
            </div>
          </div>
          <div class="input-login mb-15">
            <div>
              <div>
                <i class="fa fa-key"></i>
              </div>
              <%= f.password_field :password, placeholder: "Senha" %>
            </div>
          </div>
          <%= f.submit "Cadastrar", class: "btn btn-red btn-block" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Turismaria</title>
    <%= csrf_meta_tags %>

    <script src="/vendors/jquery/jquery.js"></script>
    <script src="/resources/scripts/main.js"></script>
    <script src="/vendors/font-awesome/fontawesome-all.js"></script>
    <link rel="stylesheet" href="/vendors/font-awesome/fa-svg-with-js.css">
    <link rel="stylesheet" href="/resources/styles/main.css">
    <link rel="stylesheet" href="/resources/bootstrap/css/bootstrap.min.css">
</head>
<body>
    <%= render "layouts/header" %>

    <%# <div id="search-box">
      <div>
        <div>
          <i class="fa fa-search"></i>
        </div>
        <input placeholder="O que está procurando?" type="text">
      </div>
    </div> %>

    <% if @banner %>
      <div id="banner">
        <div class="opacity-top"></div>
        <div class="reflection"></div>
        <img  class=""src="/resources/images/cabana.jpg">
        <div class="opacity-bottom"></div>
      </div>
    <% end %>

    <% if flash[:notice] && flash[:notice]['status'] %>
      <div class="container">
        <div class="alert alert-<%= flash[:notice]['status'] %> mt-30" role="alert">
          <%= flash[:notice]['msg'].gsub(/\n/, '<br/>').html_safe %>
        </div>
      </div>
    <% end %>

    <%= yield %>

    <%= render "layouts/modals" %>
  </body>
</html>